//! TU3 82B98F70 records, re-extracted from original bytes and all 270 map inserts.
// Each tuple is (gesture key, normal intent, mirrored intent, dark-catch category).
pub(super) const TABLES: [&[(&str, &str, &str, u32)]; 7] = [
    &[
        ("Ollie", "Ollie", "Ollie", 1),
        ("PopShuvit", "PopShuvit", "FSPopShuvit", 1),
        ("FSPopShuvit", "FSPopShuvit", "PopShuvit", 2),
        ("VarialKickflip", "VarialKickflip", "VarialHeelflip", 1),
        ("VarialHeelflip", "VarialHeelflip", "VarialKickflip", 2),
        ("Hardflip", "Hardflip", "InwardHeelflip", 1),
        ("InwardHeelflip", "InwardHeelflip", "Hardflip", 2),
        ("360PopShuvit", "360PopShuvit", "FS360PopShuvit", 1),
        ("FS360PopShuvit", "FS360PopShuvit", "360PopShuvit", 2),
        ("360Flip", "360Flip", "Laserflip", 0),
        ("Laserflip", "Laserflip", "360Flip", 0),
        ("360Hardflip", "360Hardflip", "360InwardHeelflip", 0),
        ("360InwardHeelflip", "360InwardHeelflip", "360Hardflip", 0),
        ("Kickflip", "Kickflip", "Heelflip", 0),
        ("Heelflip", "Heelflip", "Kickflip", 0),
        ("Nollie", "Nollie", "Nollie", 3),
        ("N_PopShuvit", "N_PopShuvit", "N_FSPopShuvit", 3),
        ("N_FSPopShuvit", "N_FSPopShuvit", "N_PopShuvit", 4),
        (
            "N_VarialKickflip",
            "N_VarialKickflip",
            "N_VarialHeelflip",
            3,
        ),
        (
            "N_VarialHeelflip",
            "N_VarialHeelflip",
            "N_VarialKickflip",
            4,
        ),
        ("N_Hardflip", "N_Hardflip", "N_InwardHeelflip", 3),
        ("N_InwardHeelflip", "N_InwardHeelflip", "N_Hardflip", 4),
        ("N_360PopShuvit", "N_360PopShuvit", "N_FS360PopShuvit", 3),
        ("N_FS360PopShuvit", "N_FS360PopShuvit", "N_360PopShuvit", 4),
        ("N_360Flip", "N_360Flip", "N_Laserflip", 0),
        ("N_Laserflip", "N_Laserflip", "N_360Flip", 0),
        ("N_360Hardflip", "N_360Hardflip", "N_360InwardHeelflip", 0),
        (
            "N_360InwardHeelflip",
            "N_360InwardHeelflip",
            "N_360Hardflip",
            0,
        ),
        ("N_Kickflip", "N_Kickflip", "N_Heelflip", 0),
        ("N_Heelflip", "N_Heelflip", "N_Kickflip", 0),
    ],
    &[
        ("Nollie", "Nollie", "Nollie", 3),
        ("N_PopShuvit", "N_PopShuvit", "N_FSPopShuvit", 3),
        ("N_FSPopShuvit", "N_FSPopShuvit", "N_PopShuvit", 4),
        (
            "N_VarialKickflip",
            "N_VarialKickflip",
            "N_VarialHeelflip",
            3,
        ),
        (
            "N_VarialHeelflip",
            "N_VarialHeelflip",
            "N_VarialKickflip",
            4,
        ),
        ("N_Hardflip", "N_Hardflip", "N_InwardHeelflip", 3),
        ("N_InwardHeelflip", "N_InwardHeelflip", "N_Hardflip", 4),
        ("N_360PopShuvit", "N_360PopShuvit", "N_FS360PopShuvit", 3),
        ("N_FS360PopShuvit", "N_FS360PopShuvit", "N_360PopShuvit", 4),
        ("N_360Flip", "N_360Flip", "N_Laserflip", 0),
        ("N_Laserflip", "N_Laserflip", "N_360Flip", 0),
        ("N_360Hardflip", "N_360Hardflip", "N_360InwardHeelflip", 0),
        (
            "N_360InwardHeelflip",
            "N_360InwardHeelflip",
            "N_360Hardflip",
            0,
        ),
        ("N_Kickflip", "N_Kickflip", "N_Heelflip", 0),
        ("N_Heelflip", "N_Heelflip", "N_Kickflip", 0),
        ("Ollie", "Nollie", "Nollie", 3),
        ("PopShuvit", "N_PopShuvit", "N_FSPopShuvit", 3),
        ("FSPopShuvit", "N_FSPopShuvit", "N_PopShuvit", 4),
        ("VarialKickflip", "Nollie", "Nollie", 3),
        ("VarialHeelflip", "Nollie", "Nollie", 4),
        ("Hardflip", "Nollie", "Nollie", 3),
        ("InwardHeelflip", "Nollie", "Nollie", 4),
        ("360PopShuvit", "N_PopShuvit", "N_FSPopShuvit", 3),
        ("FS360PopShuvit", "N_FSPopShuvit", "N_PopShuvit", 4),
        ("360Flip", "Nollie", "Nollie", 3),
        ("Laserflip", "Nollie", "Nollie", 4),
        ("360Hardflip", "Nollie", "Nollie", 3),
        ("360InwardHeelflip", "Nollie", "Nollie", 4),
        ("Kickflip", "Nollie", "Nollie", 3),
        ("Heelflip", "Nollie", "Nollie", 4),
    ],
    &[
        ("Ollie", "Ollie", "Ollie", 1),
        ("PopShuvit", "PopShuvit", "FSPopShuvit", 1),
        ("FSPopShuvit", "FSPopShuvit", "PopShuvit", 2),
        ("VarialKickflip", "VarialKickflip", "VarialHeelflip", 1),
        ("VarialHeelflip", "VarialHeelflip", "VarialKickflip", 2),
        ("Hardflip", "Hardflip", "InwardHeelflip", 1),
        ("InwardHeelflip", "InwardHeelflip", "Hardflip", 2),
        ("360PopShuvit", "360PopShuvit", "FS360PopShuvit", 1),
        ("FS360PopShuvit", "FS360PopShuvit", "360PopShuvit", 2),
        ("360Flip", "360Flip", "Laserflip", 0),
        ("Laserflip", "Laserflip", "360Flip", 0),
        ("360Hardflip", "360Hardflip", "360InwardHeelflip", 0),
        ("360InwardHeelflip", "360InwardHeelflip", "360Hardflip", 0),
        ("Kickflip", "Kickflip", "Heelflip", 0),
        ("Heelflip", "Heelflip", "Kickflip", 0),
        ("Nollie", "Ollie", "Ollie", 1),
        ("N_PopShuvit", "PopShuvit", "FSPopShuvit", 1),
        ("N_FSPopShuvit", "FSPopShuvit", "PopShuvit", 2),
        ("N_VarialKickflip", "Ollie", "Ollie", 1),
        ("N_VarialHeelflip", "Ollie", "Ollie", 2),
        ("N_Hardflip", "Ollie", "Ollie", 1),
        ("N_InwardHeelflip", "Ollie", "Ollie", 2),
        ("N_360PopShuvit", "PopShuvit", "FSPopShuvit", 1),
        ("N_FS360PopShuvit", "FSPopShuvit", "PopShuvit", 2),
        ("N_360Flip", "Ollie", "Ollie", 1),
        ("N_Laserflip", "Ollie", "Ollie", 2),
        ("N_360Hardflip", "Ollie", "Ollie", 1),
        ("N_360InwardHeelflip", "Ollie", "Ollie", 2),
        ("N_Kickflip", "Ollie", "Ollie", 1),
        ("N_Heelflip", "Ollie", "Ollie", 2),
    ],
    &[
        ("90_Nollie", "Nollie", "Nollie", 3),
        ("90_N_PopShuvit", "N_PopShuvit", "N_FSPopShuvit", 3),
        ("90_N_FSPopShuvit", "N_FSPopShuvit", "N_PopShuvit", 4),
        (
            "90_N_VarialKickflip",
            "N_VarialKickflip",
            "N_VarialHeelflip",
            3,
        ),
        (
            "90_N_VarialHeelflip",
            "N_VarialHeelflip",
            "N_VarialKickflip",
            4,
        ),
        ("90_N_Hardflip", "N_Hardflip", "N_InwardHeelflip", 3),
        ("90_N_InwardHeelflip", "N_InwardHeelflip", "N_Hardflip", 4),
        ("90_N_360PopShuvit", "N_360PopShuvit", "N_FS360PopShuvit", 3),
        (
            "90_N_FS360PopShuvit",
            "N_FS360PopShuvit",
            "N_360PopShuvit",
            4,
        ),
        ("90_N_360Flip", "N_360Flip", "N_Laserflip", 0),
        ("90_N_Laserflip", "N_Laserflip", "N_360Flip", 0),
        (
            "90_N_360Hardflip",
            "N_360Hardflip",
            "N_360InwardHeelflip",
            0,
        ),
        (
            "90_N_360InwardHeelflip",
            "N_360InwardHeelflip",
            "N_360Hardflip",
            0,
        ),
        ("90_N_Kickflip", "N_Kickflip", "N_Heelflip", 0),
        ("90_N_Heelflip", "N_Heelflip", "N_Kickflip", 0),
        ("Nollie", "Nollie", "Nollie", 3),
        ("N_PopShuvit", "N_PopShuvit", "N_FSPopShuvit", 3),
        ("N_FSPopShuvit", "N_FSPopShuvit", "N_PopShuvit", 4),
        (
            "N_VarialKickflip",
            "N_VarialKickflip",
            "N_VarialHeelflip",
            3,
        ),
        (
            "N_VarialHeelflip",
            "N_VarialHeelflip",
            "N_VarialKickflip",
            4,
        ),
        ("N_Hardflip", "N_Hardflip", "N_InwardHeelflip", 3),
        ("N_InwardHeelflip", "N_InwardHeelflip", "N_Hardflip", 4),
        ("N_360PopShuvit", "N_360PopShuvit", "N_FS360PopShuvit", 3),
        ("N_FS360PopShuvit", "N_FS360PopShuvit", "N_360PopShuvit", 4),
        ("N_360Flip", "N_360Flip", "N_Laserflip", 0),
        ("N_Laserflip", "N_Laserflip", "N_360Flip", 0),
        ("N_360Hardflip", "N_360Hardflip", "N_360InwardHeelflip", 0),
        (
            "N_360InwardHeelflip",
            "N_360InwardHeelflip",
            "N_360Hardflip",
            0,
        ),
        ("N_Kickflip", "N_Kickflip", "N_Heelflip", 0),
        ("N_Heelflip", "N_Heelflip", "N_Kickflip", 0),
        ("Ollie", "Nollie", "Nollie", 3),
        ("PopShuvit", "N_PopShuvit", "N_FSPopShuvit", 3),
        ("FSPopShuvit", "N_FSPopShuvit", "N_PopShuvit", 4),
        ("VarialKickflip", "Nollie", "Nollie", 3),
        ("VarialHeelflip", "Nollie", "Nollie", 4),
        ("Hardflip", "Nollie", "Nollie", 3),
        ("InwardHeelflip", "Nollie", "Nollie", 4),
        ("360PopShuvit", "N_PopShuvit", "N_FSPopShuvit", 3),
        ("FS360PopShuvit", "N_FSPopShuvit", "N_PopShuvit", 4),
        ("360Flip", "Nollie", "Nollie", 3),
        ("Laserflip", "Nollie", "Nollie", 4),
        ("360Hardflip", "Nollie", "Nollie", 3),
        ("360InwardHeelflip", "Nollie", "Nollie", 4),
        ("Kickflip", "Nollie", "Nollie", 3),
        ("Heelflip", "Nollie", "Nollie", 4),
    ],
    &[
        ("90_Ollie", "Ollie", "Ollie", 1),
        ("90_PopShuvit", "PopShuvit", "FSPopShuvit", 1),
        ("90_FSPopShuvit", "FSPopShuvit", "PopShuvit", 2),
        ("90_VarialKickflip", "VarialKickflip", "VarialHeelflip", 1),
        ("90_VarialHeelflip", "VarialHeelflip", "VarialKickflip", 2),
        ("90_Hardflip", "Hardflip", "InwardHeelflip", 1),
        ("90_InwardHeelflip", "InwardHeelflip", "Hardflip", 2),
        ("90_360PopShuvit", "360PopShuvit", "FS360PopShuvit", 1),
        ("90_FS360PopShuvit", "FS360PopShuvit", "360PopShuvit", 2),
        ("90_360Flip", "360Flip", "Laserflip", 0),
        ("90_Laserflip", "Laserflip", "360Flip", 0),
        ("90_360Hardflip", "360Hardflip", "360InwardHeelflip", 0),
        (
            "90_360InwardHeelflip",
            "360InwardHeelflip",
            "360Hardflip",
            0,
        ),
        ("90_Kickflip", "Kickflip", "Heelflip", 0),
        ("90_Heelflip", "Heelflip", "Kickflip", 0),
        ("Ollie", "Ollie", "Ollie", 1),
        ("PopShuvit", "PopShuvit", "FSPopShuvit", 1),
        ("FSPopShuvit", "FSPopShuvit", "PopShuvit", 2),
        ("VarialKickflip", "VarialKickflip", "VarialHeelflip", 1),
        ("VarialHeelflip", "VarialHeelflip", "VarialKickflip", 2),
        ("Hardflip", "Hardflip", "InwardHeelflip", 1),
        ("InwardHeelflip", "InwardHeelflip", "Hardflip", 2),
        ("360PopShuvit", "360PopShuvit", "FS360PopShuvit", 1),
        ("FS360PopShuvit", "FS360PopShuvit", "360PopShuvit", 2),
        ("360Flip", "360Flip", "Laserflip", 0),
        ("Laserflip", "Laserflip", "360Flip", 0),
        ("360Hardflip", "360Hardflip", "360InwardHeelflip", 0),
        ("360InwardHeelflip", "360InwardHeelflip", "360Hardflip", 0),
        ("Kickflip", "Kickflip", "Heelflip", 0),
        ("Heelflip", "Heelflip", "Kickflip", 0),
        ("Nollie", "Ollie", "Ollie", 1),
        ("N_PopShuvit", "PopShuvit", "FSPopShuvit", 1),
        ("N_FSPopShuvit", "FSPopShuvit", "PopShuvit", 2),
        ("N_VarialKickflip", "Ollie", "Ollie", 1),
        ("N_VarialHeelflip", "Ollie", "Ollie", 2),
        ("N_Hardflip", "Ollie", "Ollie", 1),
        ("N_InwardHeelflip", "Ollie", "Ollie", 2),
        ("N_360PopShuvit", "PopShuvit", "FSPopShuvit", 1),
        ("N_FS360PopShuvit", "FSPopShuvit", "PopShuvit", 2),
        ("N_360Flip", "Ollie", "Ollie", 1),
        ("N_Laserflip", "Ollie", "Ollie", 2),
        ("N_360Hardflip", "Ollie", "Ollie", 1),
        ("N_360InwardHeelflip", "Ollie", "Ollie", 2),
        ("N_Kickflip", "Ollie", "Ollie", 1),
        ("N_Heelflip", "Ollie", "Ollie", 2),
    ],
    &[
        ("N90_Nollie", "Nollie", "Nollie", 3),
        ("N90_N_PopShuvit", "N_PopShuvit", "N_FSPopShuvit", 3),
        ("N90_N_FSPopShuvit", "N_FSPopShuvit", "N_PopShuvit", 4),
        (
            "N90_N_VarialKickflip",
            "N_VarialKickflip",
            "N_VarialHeelflip",
            3,
        ),
        (
            "N90_N_VarialHeelflip",
            "N_VarialHeelflip",
            "N_VarialKickflip",
            4,
        ),
        ("N90_N_Hardflip", "N_Hardflip", "N_InwardHeelflip", 3),
        ("N90_N_InwardHeelflip", "N_InwardHeelflip", "N_Hardflip", 4),
        (
            "N90_N_360PopShuvit",
            "N_360PopShuvit",
            "N_FS360PopShuvit",
            3,
        ),
        (
            "N90_N_FS360PopShuvit",
            "N_FS360PopShuvit",
            "N_360PopShuvit",
            4,
        ),
        ("N90_N_360Flip", "N_360Flip", "N_Laserflip", 0),
        ("N90_N_Laserflip", "N_Laserflip", "N_360Flip", 0),
        (
            "N90_N_360Hardflip",
            "N_360Hardflip",
            "N_360InwardHeelflip",
            0,
        ),
        (
            "N90_N_360InwardHeelflip",
            "N_360InwardHeelflip",
            "N_360Hardflip",
            0,
        ),
        ("N90_N_Kickflip", "N_Kickflip", "N_Heelflip", 0),
        ("N90_N_Heelflip", "N_Heelflip", "N_Kickflip", 0),
        ("Nollie", "Nollie", "Nollie", 3),
        ("N_PopShuvit", "N_PopShuvit", "N_FSPopShuvit", 3),
        ("N_FSPopShuvit", "N_FSPopShuvit", "N_PopShuvit", 4),
        (
            "N_VarialKickflip",
            "N_VarialKickflip",
            "N_VarialHeelflip",
            3,
        ),
        (
            "N_VarialHeelflip",
            "N_VarialHeelflip",
            "N_VarialKickflip",
            4,
        ),
        ("N_Hardflip", "N_Hardflip", "N_InwardHeelflip", 3),
        ("N_InwardHeelflip", "N_InwardHeelflip", "N_Hardflip", 4),
        ("N_360PopShuvit", "N_360PopShuvit", "N_FS360PopShuvit", 3),
        ("N_FS360PopShuvit", "N_FS360PopShuvit", "N_360PopShuvit", 4),
        ("N_360Flip", "N_360Flip", "N_Laserflip", 0),
        ("N_Laserflip", "N_Laserflip", "N_360Flip", 0),
        ("N_360Hardflip", "N_360Hardflip", "N_360InwardHeelflip", 0),
        (
            "N_360InwardHeelflip",
            "N_360InwardHeelflip",
            "N_360Hardflip",
            0,
        ),
        ("N_Kickflip", "N_Kickflip", "N_Heelflip", 0),
        ("N_Heelflip", "N_Heelflip", "N_Kickflip", 0),
        ("Ollie", "Nollie", "Nollie", 3),
        ("PopShuvit", "N_PopShuvit", "N_FSPopShuvit", 3),
        ("FSPopShuvit", "N_FSPopShuvit", "N_PopShuvit", 4),
        ("VarialKickflip", "Nollie", "Nollie", 3),
        ("VarialHeelflip", "Nollie", "Nollie", 4),
        ("Hardflip", "Nollie", "Nollie", 3),
        ("InwardHeelflip", "Nollie", "Nollie", 4),
        ("360PopShuvit", "N_PopShuvit", "N_FSPopShuvit", 3),
        ("FS360PopShuvit", "N_FSPopShuvit", "N_PopShuvit", 4),
        ("360Flip", "Nollie", "Nollie", 3),
        ("Laserflip", "Nollie", "Nollie", 4),
        ("360Hardflip", "Nollie", "Nollie", 3),
        ("360InwardHeelflip", "Nollie", "Nollie", 4),
        ("Kickflip", "Nollie", "Nollie", 3),
        ("Heelflip", "Nollie", "Nollie", 4),
    ],
    &[
        ("N90_Ollie", "Ollie", "Ollie", 1),
        ("N90_PopShuvit", "PopShuvit", "FSPopShuvit", 1),
        ("N90_FSPopShuvit", "FSPopShuvit", "PopShuvit", 2),
        ("N90_VarialKickflip", "VarialKickflip", "VarialHeelflip", 1),
        ("N90_VarialHeelflip", "VarialHeelflip", "VarialKickflip", 2),
        ("N90_Hardflip", "Hardflip", "InwardHeelflip", 1),
        ("N90_InwardHeelflip", "InwardHeelflip", "Hardflip", 2),
        ("N90_360PopShuvit", "360PopShuvit", "FS360PopShuvit", 1),
        ("N90_FS360PopShuvit", "FS360PopShuvit", "360PopShuvit", 2),
        ("N90_360Flip", "360Flip", "Laserflip", 0),
        ("N90_Laserflip", "Laserflip", "360Flip", 0),
        ("N90_360Hardflip", "360Hardflip", "360InwardHeelflip", 0),
        (
            "N90_360InwardHeelflip",
            "360InwardHeelflip",
            "360Hardflip",
            0,
        ),
        ("N90_Kickflip", "Kickflip", "Heelflip", 0),
        ("N90_Heelflip", "Heelflip", "Kickflip", 0),
        ("Ollie", "Ollie", "Ollie", 1),
        ("PopShuvit", "PopShuvit", "FSPopShuvit", 1),
        ("FSPopShuvit", "FSPopShuvit", "PopShuvit", 2),
        ("VarialKickflip", "VarialKickflip", "VarialHeelflip", 1),
        ("VarialHeelflip", "VarialHeelflip", "VarialKickflip", 2),
        ("Hardflip", "Hardflip", "InwardHeelflip", 1),
        ("InwardHeelflip", "InwardHeelflip", "Hardflip", 2),
        ("360PopShuvit", "360PopShuvit", "FS360PopShuvit", 1),
        ("FS360PopShuvit", "FS360PopShuvit", "360PopShuvit", 2),
        ("360Flip", "360Flip", "Laserflip", 0),
        ("Laserflip", "Laserflip", "360Flip", 0),
        ("360Hardflip", "360Hardflip", "360InwardHeelflip", 0),
        ("360InwardHeelflip", "360InwardHeelflip", "360Hardflip", 0),
        ("Kickflip", "Kickflip", "Heelflip", 0),
        ("Heelflip", "Heelflip", "Kickflip", 0),
        ("Nollie", "Ollie", "Ollie", 1),
        ("N_PopShuvit", "PopShuvit", "FSPopShuvit", 1),
        ("N_FSPopShuvit", "FSPopShuvit", "PopShuvit", 2),
        ("N_VarialKickflip", "Ollie", "Ollie", 1),
        ("N_VarialHeelflip", "Ollie", "Ollie", 2),
        ("N_Hardflip", "Ollie", "Ollie", 1),
        ("N_InwardHeelflip", "Ollie", "Ollie", 2),
        ("N_360PopShuvit", "PopShuvit", "FSPopShuvit", 1),
        ("N_FS360PopShuvit", "FSPopShuvit", "PopShuvit", 2),
        ("N_360Flip", "Ollie", "Ollie", 1),
        ("N_Laserflip", "Ollie", "Ollie", 2),
        ("N_360Hardflip", "Ollie", "Ollie", 1),
        ("N_360InwardHeelflip", "Ollie", "Ollie", 2),
        ("N_Kickflip", "Ollie", "Ollie", 1),
        ("N_Heelflip", "Ollie", "Ollie", 2),
    ],
];
