use super::Name;
pub(super) const TABLE: [Name; 48] = [
    Name {
        skating_id: 3,
        attribute: "FS_50_50",
        display: "FS 50-50",
        scorable_id: 23,
    },
    Name {
        skating_id: 1,
        attribute: "FS_LIP",
        display: "FS Lipslide",
        scorable_id: 28,
    },
    Name {
        skating_id: 13,
        attribute: "FS_NOSEBLUNT",
        display: "FS Noseblunt",
        scorable_id: 29,
    },
    Name {
        skating_id: 6,
        attribute: "FS_NOSEGRIND",
        display: "FS Nosegrind",
        scorable_id: 30,
    },
    Name {
        skating_id: 13,
        attribute: "FS_NOSEBLUNT",
        display: "FS Noseblunt",
        scorable_id: 29,
    },
    Name {
        skating_id: 17,
        attribute: "FS_DARKSLIDE",
        display: "FS Darkslide",
        scorable_id: 270,
    },
    Name {
        skating_id: 3,
        attribute: "FS_50_50",
        display: "FS 50-50",
        scorable_id: 23,
    },
    Name {
        skating_id: 2,
        attribute: "FS_BOARD",
        display: "FS Boardslide",
        scorable_id: 25,
    },
    Name {
        skating_id: 4,
        attribute: "FS_NOSESLIDE",
        display: "FS Noseslide",
        scorable_id: 31,
    },
    Name {
        skating_id: 6,
        attribute: "FS_NOSEGRIND",
        display: "FS Nosegrind",
        scorable_id: 30,
    },
    Name {
        skating_id: 30,
        attribute: "BS_NOSEBLUNT",
        display: "BS Noseblunt",
        scorable_id: 13,
    },
    Name {
        skating_id: 34,
        attribute: "BS_DARKSLIDE",
        display: "BS Darkslide",
        scorable_id: 270,
    },
    Name {
        skating_id: 35,
        attribute: "BF_FS_50_50",
        display: "FS 50-50",
        scorable_id: 23,
    },
    Name {
        skating_id: 1,
        attribute: "FS_LIP",
        display: "FS Lipslide",
        scorable_id: 28,
    },
    Name {
        skating_id: 13,
        attribute: "FS_NOSEBLUNT",
        display: "FS Noseblunt",
        scorable_id: 29,
    },
    Name {
        skating_id: 36,
        attribute: "BF_FS_NOSEGRIND",
        display: "FS Nosegrind",
        scorable_id: 30,
    },
    Name {
        skating_id: 13,
        attribute: "FS_NOSEBLUNT",
        display: "FS Noseblunt",
        scorable_id: 29,
    },
    Name {
        skating_id: 17,
        attribute: "FS_DARKSLIDE",
        display: "FS Darkslide",
        scorable_id: 270,
    },
    Name {
        skating_id: 35,
        attribute: "BF_FS_50_50",
        display: "FS 50-50",
        scorable_id: 23,
    },
    Name {
        skating_id: 2,
        attribute: "FS_BOARD",
        display: "FS Boardslide",
        scorable_id: 25,
    },
    Name {
        skating_id: 4,
        attribute: "FS_NOSESLIDE",
        display: "FS Noseslide",
        scorable_id: 31,
    },
    Name {
        skating_id: 36,
        attribute: "BF_FS_NOSEGRIND",
        display: "FS Nosegrind",
        scorable_id: 30,
    },
    Name {
        skating_id: 30,
        attribute: "BS_NOSEBLUNT",
        display: "BS Noseblunt",
        scorable_id: 13,
    },
    Name {
        skating_id: 34,
        attribute: "BS_DARKSLIDE",
        display: "BS Darkslide",
        scorable_id: 270,
    },
    Name {
        skating_id: 3,
        attribute: "FS_50_50",
        display: "FS 50-50",
        scorable_id: 23,
    },
    Name {
        skating_id: 1,
        attribute: "FS_LIP",
        display: "FS Lipslide",
        scorable_id: 28,
    },
    Name {
        skating_id: 13,
        attribute: "FS_NOSEBLUNT",
        display: "FS Noseblunt",
        scorable_id: 29,
    },
    Name {
        skating_id: 12,
        attribute: "FS_OVERWILLY",
        display: "FS Over Willy",
        scorable_id: 33,
    },
    Name {
        skating_id: 13,
        attribute: "FS_NOSEBLUNT",
        display: "FS Noseblunt",
        scorable_id: 29,
    },
    Name {
        skating_id: 17,
        attribute: "FS_DARKSLIDE",
        display: "FS Darkslide",
        scorable_id: 270,
    },
    Name {
        skating_id: 3,
        attribute: "FS_50_50",
        display: "FS 50-50",
        scorable_id: 23,
    },
    Name {
        skating_id: 2,
        attribute: "FS_BOARD",
        display: "FS Boardslide",
        scorable_id: 25,
    },
    Name {
        skating_id: 4,
        attribute: "FS_NOSESLIDE",
        display: "FS Noseslide",
        scorable_id: 31,
    },
    Name {
        skating_id: 11,
        attribute: "FS_WILLY",
        display: "FS Willy",
        scorable_id: 37,
    },
    Name {
        skating_id: 30,
        attribute: "BS_NOSEBLUNT",
        display: "BS Noseblunt",
        scorable_id: 13,
    },
    Name {
        skating_id: 34,
        attribute: "BS_DARKSLIDE",
        display: "BS Darkslide",
        scorable_id: 270,
    },
    Name {
        skating_id: 35,
        attribute: "BF_FS_50_50",
        display: "FS 50-50",
        scorable_id: 23,
    },
    Name {
        skating_id: 1,
        attribute: "FS_LIP",
        display: "FS Lipslide",
        scorable_id: 28,
    },
    Name {
        skating_id: 13,
        attribute: "FS_NOSEBLUNT",
        display: "FS Noseblunt",
        scorable_id: 29,
    },
    Name {
        skating_id: 42,
        attribute: "BF_FS_OVERWILLY",
        display: "FS Over Willy",
        scorable_id: 33,
    },
    Name {
        skating_id: 13,
        attribute: "FS_NOSEBLUNT",
        display: "FS Noseblunt",
        scorable_id: 29,
    },
    Name {
        skating_id: 17,
        attribute: "FS_DARKSLIDE",
        display: "FS Darkslide",
        scorable_id: 270,
    },
    Name {
        skating_id: 35,
        attribute: "BF_FS_50_50",
        display: "FS 50-50",
        scorable_id: 23,
    },
    Name {
        skating_id: 2,
        attribute: "FS_BOARD",
        display: "FS Boardslide",
        scorable_id: 25,
    },
    Name {
        skating_id: 4,
        attribute: "FS_NOSESLIDE",
        display: "FS Noseslide",
        scorable_id: 31,
    },
    Name {
        skating_id: 41,
        attribute: "BF_FS_WILLY",
        display: "FS Willy",
        scorable_id: 37,
    },
    Name {
        skating_id: 30,
        attribute: "BS_NOSEBLUNT",
        display: "BS Noseblunt",
        scorable_id: 13,
    },
    Name {
        skating_id: 34,
        attribute: "BS_DARKSLIDE",
        display: "BS Darkslide",
        scorable_id: 270,
    },
];
