use super::Name;
pub(super) const TABLE: [Name; 48] = [
    Name {
        skating_id: 20,
        attribute: "BS_50_50",
        display: "BS 50-50",
        scorable_id: 7,
    },
    Name {
        skating_id: 19,
        attribute: "BS_BOARD",
        display: "BS Boardslide",
        scorable_id: 9,
    },
    Name {
        skating_id: 21,
        attribute: "BS_NOSESLIDE",
        display: "BS Noseslide",
        scorable_id: 15,
    },
    Name {
        skating_id: 32,
        attribute: "BS_CROOK",
        display: "BS Crooked",
        scorable_id: 10,
    },
    Name {
        skating_id: 13,
        attribute: "FS_NOSEBLUNT",
        display: "FS Noseblunt",
        scorable_id: 29,
    },
    Name {
        skating_id: 17,
        attribute: "FS_DARKSLIDE",
        display: "FS Darkslide",
        scorable_id: 269,
    },
    Name {
        skating_id: 20,
        attribute: "BS_50_50",
        display: "BS 50-50",
        scorable_id: 7,
    },
    Name {
        skating_id: 18,
        attribute: "BS_LIP",
        display: "BS Lipslide",
        scorable_id: 12,
    },
    Name {
        skating_id: 30,
        attribute: "BS_NOSEBLUNT",
        display: "BS Noseblunt",
        scorable_id: 13,
    },
    Name {
        skating_id: 33,
        attribute: "BS_OVERCROOK",
        display: "BS Overcrooks",
        scorable_id: 16,
    },
    Name {
        skating_id: 30,
        attribute: "BS_NOSEBLUNT",
        display: "BS Noseblunt",
        scorable_id: 13,
    },
    Name {
        skating_id: 34,
        attribute: "BS_DARKSLIDE",
        display: "BS Darkslide",
        scorable_id: 269,
    },
    Name {
        skating_id: 45,
        attribute: "BF_BS_50_50",
        display: "BS 50-50",
        scorable_id: 7,
    },
    Name {
        skating_id: 19,
        attribute: "BS_BOARD",
        display: "BS Boardslide",
        scorable_id: 9,
    },
    Name {
        skating_id: 21,
        attribute: "BS_NOSESLIDE",
        display: "BS Noseslide",
        scorable_id: 15,
    },
    Name {
        skating_id: 53,
        attribute: "BF_BS_CROOK",
        display: "BS Crooked",
        scorable_id: 10,
    },
    Name {
        skating_id: 13,
        attribute: "FS_NOSEBLUNT",
        display: "FS Noseblunt",
        scorable_id: 29,
    },
    Name {
        skating_id: 17,
        attribute: "FS_DARKSLIDE",
        display: "FS Darkslide",
        scorable_id: 269,
    },
    Name {
        skating_id: 45,
        attribute: "BF_BS_50_50",
        display: "BS 50-50",
        scorable_id: 7,
    },
    Name {
        skating_id: 18,
        attribute: "BS_LIP",
        display: "BS Lipslide",
        scorable_id: 12,
    },
    Name {
        skating_id: 30,
        attribute: "BS_NOSEBLUNT",
        display: "BS Noseblunt",
        scorable_id: 13,
    },
    Name {
        skating_id: 54,
        attribute: "BF_BS_OVERCROOK",
        display: "BS Overcrooks",
        scorable_id: 16,
    },
    Name {
        skating_id: 30,
        attribute: "BS_NOSEBLUNT",
        display: "BS Noseblunt",
        scorable_id: 13,
    },
    Name {
        skating_id: 34,
        attribute: "BS_DARKSLIDE",
        display: "BS Darkslide",
        scorable_id: 269,
    },
    Name {
        skating_id: 20,
        attribute: "BS_50_50",
        display: "BS 50-50",
        scorable_id: 7,
    },
    Name {
        skating_id: 19,
        attribute: "BS_BOARD",
        display: "BS Boardslide",
        scorable_id: 9,
    },
    Name {
        skating_id: 21,
        attribute: "BS_NOSESLIDE",
        display: "BS Noseslide",
        scorable_id: 15,
    },
    Name {
        skating_id: 28,
        attribute: "BS_WILLY",
        display: "BS Willy",
        scorable_id: 21,
    },
    Name {
        skating_id: 13,
        attribute: "FS_NOSEBLUNT",
        display: "FS_Noseblunt",
        scorable_id: 29,
    },
    Name {
        skating_id: 17,
        attribute: "FS_DARKSLIDE",
        display: "FS_Darkslide",
        scorable_id: 269,
    },
    Name {
        skating_id: 20,
        attribute: "BS_50_50",
        display: "BS 50-50",
        scorable_id: 7,
    },
    Name {
        skating_id: 18,
        attribute: "BS_LIP",
        display: "BS Lipslide",
        scorable_id: 12,
    },
    Name {
        skating_id: 30,
        attribute: "BS_NOSEBLUNT",
        display: "BS Noseblunt",
        scorable_id: 13,
    },
    Name {
        skating_id: 29,
        attribute: "BS_OVERWILLY",
        display: "BS Overwilly",
        scorable_id: 17,
    },
    Name {
        skating_id: 30,
        attribute: "BS_NOSEBLUNT",
        display: "BS Noseblunt",
        scorable_id: 13,
    },
    Name {
        skating_id: 34,
        attribute: "BS_DARKSLIDE",
        display: "BS Darkslide",
        scorable_id: 269,
    },
    Name {
        skating_id: 45,
        attribute: "BF_BS_50_50",
        display: "BS 50-50",
        scorable_id: 7,
    },
    Name {
        skating_id: 19,
        attribute: "BS_BOARD",
        display: "BS Boardslide",
        scorable_id: 9,
    },
    Name {
        skating_id: 21,
        attribute: "BS_NOSESLIDE",
        display: "BS Noseslide",
        scorable_id: 15,
    },
    Name {
        skating_id: 51,
        attribute: "BF_BS_WILLY",
        display: "BS Willy",
        scorable_id: 21,
    },
    Name {
        skating_id: 13,
        attribute: "FS_NOSEBLUNT",
        display: "FS_Noseblunt",
        scorable_id: 29,
    },
    Name {
        skating_id: 17,
        attribute: "FS_DARKSLIDE",
        display: "FS_Darkslide",
        scorable_id: 269,
    },
    Name {
        skating_id: 45,
        attribute: "BF_BS_50_50",
        display: "BS 50-50",
        scorable_id: 7,
    },
    Name {
        skating_id: 18,
        attribute: "BS_LIP",
        display: "BS Lipslide",
        scorable_id: 12,
    },
    Name {
        skating_id: 30,
        attribute: "BS_NOSEBLUNT",
        display: "BS Noseblunt",
        scorable_id: 13,
    },
    Name {
        skating_id: 52,
        attribute: "BF_BS_OVERWILLY",
        display: "BS Overwilly",
        scorable_id: 17,
    },
    Name {
        skating_id: 30,
        attribute: "BS_NOSEBLUNT",
        display: "BS Noseblunt",
        scorable_id: 13,
    },
    Name {
        skating_id: 34,
        attribute: "BS_DARKSLIDE",
        display: "BS Darkslide",
        scorable_id: 269,
    },
];
